app:
  kafka:
    topics:
      user-registered: "${USER_REGISTERED_TOPIC:user-registered-topic}"

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: "${KAFKA_CONSUMER_GROUP:email-service-group}"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer  # ← ИЗМЕНИТЬ
      properties:
        # УБРАТЬ ErrorHandlingDeserializer настройки
        spring.json.trusted.packages: "*"

  mail:
    host: "${SMTP_HOST:smtp.gmail.com}"
    port: "${SMTP_PORT:587}"
    username: "${SMTP_USERNAME:test@gmail.com}"
    password: "${SMTP_PASSWORD:eqfx hplv ctat thnx}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

server:
  port: 8085

logging:
  level:
    org.springframework: INFO
    by.pasha.emailservice: DEBUG